import type { Metadata } from "next";
import { Inter, Prompt } from "next/font/google";

import "./globals.css";

// Load Inter font for English text
const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const promptThai = Prompt({
	variable: "--font-prompt", // แก้จาก --font-promt เป็น --font-prompt
	subsets: ["thai"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${inter.variable}  ${promptThai.variable} `}>
			<body>{children}</body>
		</html>
	);
}
