export const dealershipSchema = {
	"@context": "https://schema.org",
	"@type": "AutoDealer",
	name: "BYD Metromobile",
	description:
		"ศูนย์รถยนต์ไฟฟ้า BYD อย่างเป็นทางการ ครอบคลุมทั้งการขาย บริการ และศูนย์บริการหลังการขาย",
	url: "https://bydmetromobile.com",
	sameAs: [
		"https://facebook.com/bydmetromobile",
		"https://instagram.com/bydmetromobile",
	],
	telephone: "+66-2-291-8889",
	priceRange: "฿569,900 - ฿1,249,900",
	department: [
		{
			"@type": "AutoDealer",
			name: "BYD Metromobile สาขาพระราม 3",
			description: "ศูนย์รถยนต์ไฟฟ้า BYD สาขาพระราม 3",
			url: "https://bydmetromobile.com/rama3",
			address: {
				"@type": "PostalAddress",
				streetAddress: "พระราม 3",
				addressLocality: "กรุงเทพมหานคร",
				postalCode: "10120",
				addressCountry: "TH",
			},
			geo: {
				"@type": "GeoCoordinates",
				latitude: "13.6898373",
				longitude: "100.511054",
			},
			openingHoursSpecification: [
				{
					"@type": "OpeningHoursSpecification",
					dayOfWeek: [
						"Monday",
						"Tuesday",
						"Wednesday",
						"Thursday",
						"Friday",
						"Saturday",
						"Sunday",
					],
					opens: "09:00",
					closes: "18:00",
				},
			],
			telephone: "02-291-8889",
		},
		{
			"@type": "AutoDealer",
			name: "BYD Metromobile สาขาตลิ่งชัน",
			description: "ศูนย์รถยนต์ไฟฟ้า BYD สาขาตลิ่งชัน",
			url: "https://bydmetromobile.com/talingchan",
			address: {
				"@type": "PostalAddress",
				streetAddress: "ตลิ่งชัน",
				addressLocality: "กรุงเทพมหานคร",
				postalCode: "10170",
				addressCountry: "TH",
			},
			geo: {
				"@type": "GeoCoordinates",
				latitude: "13.776053",
				longitude: "100.40893499999999",
			},
			openingHoursSpecification: [
				{
					"@type": "OpeningHoursSpecification",
					dayOfWeek: [
						"Monday",
						"Tuesday",
						"Wednesday",
						"Thursday",
						"Friday",
						"Saturday",
						"Sunday",
					],
					opens: "09:00",
					closes: "18:00",
				},
			],
			telephone: "02-448-3999",
		},
		{
			"@type": "AutoDealer",
			name: "BYD Metromobile สาขาอ่อนนุช",
			description: "ศูนย์รถยนต์ไฟฟ้า BYD สาขาอ่อนนุช",
			url: "https://bydmetromobile.com/onnut",
			address: {
				"@type": "PostalAddress",
				streetAddress: "อ่อนนุช",
				addressLocality: "กรุงเทพมหานคร",
				postalCode: "10250",
				addressCountry: "TH",
			},
			geo: {
				"@type": "GeoCoordinates",
				latitude: "13.722032",
				longitude: "100.70593",
			},
			openingHoursSpecification: [
				{
					"@type": "OpeningHoursSpecification",
					dayOfWeek: [
						"Monday",
						"Tuesday",
						"Wednesday",
						"Thursday",
						"Friday",
						"Saturday",
						"Sunday",
					],
					opens: "09:00",
					closes: "18:00",
				},
			],
			telephone: "080-416-1888",
		},
		{
			"@type": "AutoDealer",
			name: "BYD Metromobile สาขารามอินทรา กม.9",
			description: "ศูนย์รถยนต์ไฟฟ้า BYD สาขารามอินทรา กม.9",
			url: "https://bydmetromobile.com/ramindra",
			address: {
				"@type": "PostalAddress",
				streetAddress: "รามอินทรา กม.9",
				addressLocality: "กรุงเทพมหานคร",
				postalCode: "10230",
				addressCountry: "TH",
			},
			geo: {
				"@type": "GeoCoordinates",
				latitude: "13.832594395359672",
				longitude: "100.66649121169309",
			},
			openingHoursSpecification: [
				{
					"@type": "OpeningHoursSpecification",
					dayOfWeek: [
						"Monday",
						"Tuesday",
						"Wednesday",
						"Thursday",
						"Friday",
						"Saturday",
						"Sunday",
					],
					opens: "09:00",
					closes: "18:00",
				},
			],
			telephone: "081-665-6888",
		},
	],
};
